### ISSUE TITLE
Can't use nebula core

### ISSUE THREAD

**Issue by matcaampos** [aidan-harding/nebula-core#3]
Hi aidan, i read the documentation of the nebula, and I installed in a org to test, but all the classes including the metadata types comes with nebc__ in front of the classes, and the classes don't compile because the file have a name and the class don't have the same name... 

Pls, What i'm doing wrong? Can you help me with this?

![image](https://user-images.githubusercontent.com/41803840/152429787-b75ea4c7-136b-4bdf-982c-799f8e1168f2.png)

**Comment by aidan-harding** [comment]
Hi @matcaampos,

Nebula Core is packaged as a namespace unlocked package. This is ideal for distributing open-source projects, but not all that widely used. Your editor shouldn't be letting you try to edit the files because the namespace prevents you from editing them after installation. 

How did you install it into your org? Did you install the package? Or clone the source code?

It looks like it might just be your IDE getting confused? Is that VS Code that you have? Are you downloading the metadata with `sfdx force:source` commands? If so, you might be able to solve this by adding to your `.forceignore` file to exclude the nebc namespace.

We all use Illuminated Cloud - in the old days, that would download the source for namespaced unlocked packages like Nebula Core. But we reported it, and the tool changed to stop doing that. Today, Illuminated Cloud recognises the class names to give you auto-complete with Nebula Core installed, but it doesn't download the code so there's no confusion. 

Hopefully we can get this working with a bit more info...

**Comment by matcaampos** [comment]
Hello Aidan, thanks for answer me. I'll explain what happened to me.

I installed nebula-core in my trailhead org, to study the classes and the use of the nebula-core classes and concepts.

I installed from the link:

![image](https://user-images.githubusercontent.com/41803840/152526445-34d45847-f952-47e8-b59e-e268716cbcf3.png)

Now the classes are in my org.

![image](https://user-images.githubusercontent.com/41803840/152526659-dca6c292-8e9d-4591-87a8-c3bed1d97a80.png)

But I can't use the classes, I create a test class to test some of the classes of nebula core installed in my org, but it's like the class don't installed ok, or like the classes don't compile, because of the name in the file have the 'nebc__' and the class don't have the same name....

![image](https://user-images.githubusercontent.com/41803840/152526863-8163a21d-2d11-45e6-ac16-b63753b12397.png)

![image](https://user-images.githubusercontent.com/41803840/152526904-ae3db91e-8120-4873-b0d3-9e3547f710ef.png)

Please Aidan, i think i'm doing something wrong, but i don't know what...

Questions?

To use nebula-core i have to rename all the files?

**Comment by matcaampos** [comment]
Hi Aidan, I'm compile the classes and now i'm able to use, sorry about that.

**Comment by matcaampos** [comment]
Hi aidan, my bad man, I forget the reference of namespace 

![image](https://user-images.githubusercontent.com/41803840/152542157-3b99941d-2227-48d6-85fb-9ea90c156e34.png)

**Comment by aidan-harding** [comment]
You got it... Adding the namespace reference is exactly what you needed 😀

I hope you find Nebula Core interesting and/or useful!
