### ISSUE TITLE
IsFieldChangedInTrigger to support String fields

### ISSUE THREAD

**Issue by DanBeerNebula** [aidan-harding/nebula-core#32]
IsFieldChangedInTrigger only supports SObjectField, please change it to support String fields or add the below class that I've been using.

We need string fields to prevent the pointless conversion to SObjectFields when retrieving a list of fields from other methods such as get all source fields from the transformer.

```
public with sharing class IsStringFieldChangedInTrigger extends nebc.TriggerContextBooleanFunction  {

    private String field;

    public IsStringFieldChangedInTrigger(String field) {
        this.field = field;
    }

    public override Boolean isTrueFor(SObject oldRecord, SObject newRecord) {
        return oldRecord == null || oldRecord.get(field) != newRecord.get(field);
    }
}
```

**Comment by aidan-harding** [comment]
Do you think that being able to read nested fields like 'Account.Parent.Name' matters here?

I think not because generally we're dealing with trigger contexts and they would never have a nested field. 

If we don't allow nested fields, then the neatest thing is to add extra constructors to the existing classes. That gets my vote, but what do you think?
